services:
  frontend:
    build: .
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # A MÁGICA: Conecta seus arquivos direto no Nginx. Salve no VS Code e dê F5 no site!
      - .:/usr/share/nginx/html
    depends_on:
      - api

  api:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - banco-dados:/app/data
    command: sh -c "if [ ! -f /app/data/db.json ]; then echo '{\"atletas\":[]}' > /app/data/db.json; fi && npx -y json-server@0.17.4 --watch /app/data/db.json --port 3000 --host 0.0.0.0"

volumes:
  banco-dados: